version: '2'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "devops-code/backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "devops-code/frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
